<?php

namespace SocialSyncEngine\SocialHandlers;

use GuzzleHttp\Client;
use GuzzleHttp\Exception\GuzzleException;

/**
 * Abstract base class for all social platform handlers.
 *
 * To add a new platform (e.g. Instagram, X) create a new class that extends
 * this one and implements all abstract methods.
 */
abstract class AbstractSocialHandler {

    /** @var Client Guzzle HTTP client. */
    protected Client $http;

    /** @var string WordPress options key prefix for this platform. */
    protected string $option_prefix;

    public function __construct() {
        $this->http = new Client( [ 'timeout' => 60, 'http_errors' => false ] );
    }

    // -------------------------------------------------------------------------
    // Abstract interface – must be implemented by every platform handler.
    // -------------------------------------------------------------------------

    /** Human-readable platform name. */
    abstract public function get_platform_name(): string;

    /**
     * Return the OAuth 2.0 authorization URL to redirect the user to.
     *
     * @param string $state  A random CSRF token generated by the caller.
     * @return string
     */
    abstract public function get_auth_url( string $state ): string;

    /**
     * Exchange an authorization code for (long-lived) access + refresh tokens
     * and persist them in wp_options.
     *
     * @param string $code Authorization code from the OAuth callback.
     * @return array{success: bool, error?: string}
     */
    abstract public function exchange_code_for_token( string $code ): array;

    /**
     * Attempt to refresh the stored access token using a stored refresh token.
     *
     * @return bool True on success.
     */
    abstract public function refresh_token(): bool;

    /**
     * Post a text-only update.
     *
     * @param string              $caption Caption text.
     * @param array<string,mixed> $privacy  Privacy/visibility settings.
     * @return array{success: bool, post_id?: string, error?: string}
     */
    abstract public function post_text( string $caption, array $privacy ): array;

    /**
     * Upload an image and publish a post.
     *
     * @param string              $caption   Caption text.
     * @param string              $file_path Absolute server path to the file.
     * @param string              $mime_type MIME type (e.g. image/jpeg).
     * @param array<string,mixed> $privacy   Privacy/visibility settings.
     * @return array{success: bool, post_id?: string, error?: string}
     */
    abstract public function post_image(
        string $caption,
        string $file_path,
        string $mime_type,
        array  $privacy
    ): array;

    /**
     * Upload a video using chunked / resumable upload and publish a post.
     *
     * @param string              $caption   Caption text.
     * @param string              $file_path Absolute server path to the file.
     * @param string              $mime_type MIME type (e.g. video/mp4).
     * @param array<string,mixed> $privacy   Privacy/visibility settings.
     * @return array{success: bool, post_id?: string, error?: string}
     */
    abstract public function post_video(
        string $caption,
        string $file_path,
        string $mime_type,
        array  $privacy
    ): array;

    /**
     * Check whether a valid (non-empty) access token is stored.
     */
    abstract public function is_connected(): bool;

    /**
     * Remove all stored tokens for this platform (disconnect).
     */
    abstract public function disconnect(): void;

    // -------------------------------------------------------------------------
    // Shared helpers available to all platform implementations.
    // -------------------------------------------------------------------------

    /**
     * Retrieve a stored option value for this platform.
     */
    protected function get_option( string $key, mixed $default = '' ): mixed {
        return get_option( "{$this->option_prefix}_{$key}", $default );
    }

    /**
     * Persist an option value for this platform.
     */
    protected function set_option( string $key, mixed $value ): void {
        update_option( "{$this->option_prefix}_{$key}", $value );
    }

    /**
     * Delete a stored option value for this platform.
     */
    protected function delete_option( string $key ): void {
        delete_option( "{$this->option_prefix}_{$key}" );
    }

    /**
     * Return the stored access token (or empty string if not set).
     */
    protected function get_access_token(): string {
        return (string) $this->get_option( 'access_token' );
    }

    /**
     * Build a standardised error response array.
     */
    protected function error( string $message ): array {
        return [ 'success' => false, 'error' => $message ];
    }

    /**
     * Build a standardised success response array.
     */
    protected function success( string $post_id = '' ): array {
        return array_filter( [ 'success' => true, 'post_id' => $post_id ] );
    }
}
